conv_dims: [384, 384, 384, 384]
kernel_sizes: [8, 16, 32, 64]
dense_dims: [1024, 1024]

optimiser: sgd
opt_params:
  momentum: 0.8
  weight_decay: 0.001
learning_rate: 0.001
loss: cross_entropy
n_classes: -1
