# Read the Docs configuration file
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
sphinx:
  builder: html
  configuration: docs/conf.py
python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - all
  - requirements: docs/requirements.txt
submodules:
  include: []
  recursive: false
