# Builds the auDeep docker image to use old TensorFlow 1.x.
FROM tensorflow/tensorflow:1.15.2-gpu

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libsndfile1 less vim-nox \
    && apt-get autoremove

WORKDIR /home/audeep
COPY setup.py DESCRIPTION.md /home/audeep/
COPY audeep /home/audeep/audeep
RUN python3 setup.py install \
    && rm -rf /home/audeep

WORKDIR /work
