"""Resets the filenames and adds correct label information to a dataset
generated by the auDeep spectrogram generation script.
"""

import sys
from pathlib import Path

import netCDF4
import numpy as np
import pandas as pd


def main():
    df = pd.read_csv(sys.argv[2], index_col=False, dtype='str')
    df = df.set_index(df.columns[0])
    labels = df.to_dict()[df.columns[0]]

    dataset = netCDF4.Dataset(sys.argv[1], 'a')
    names = [Path(x).stem for x in dataset.variables['filename']]
    label_arr = [labels[x] for x in names]
    dataset.variables['label_nominal'] = np.array(label_arr)
    dataset.variables['filename'] = np.array(names)
    dataset.close()
    print("Added labels to {} in {}".format(dataset.corpus, sys.argv[1]))


if __name__ == "__main__":
    main()
