# C = 2^(-6) to 2^6 in multiples of 4, same as for SVM
C: [0.015625, 0.0625, 0.25, 1.0, 4.0, 16.0, 64.0]

penalty: [l2]
class_weight: [null]
solver: [lbfgs]
max_iter: [100]
multi_class: [multinomial]
